// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/tmitry/shorturl/internal/app/repositories (interfaces: Repository)

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	reflect "reflect"

	gomock "github.com/golang/mock/gomock"
	uuid "github.com/google/uuid"
	models "github.com/tmitry/shorturl/internal/app/models"
)

// MockRepository is a mock of Repository interface.
type MockRepository struct {
	ctrl     *gomock.Controller
	recorder *MockRepositoryMockRecorder
}

// MockRepositoryMockRecorder is the mock recorder for MockRepository.
type MockRepositoryMockRecorder struct {
	mock *MockRepository
}

// NewMockRepository creates a new mock instance.
func NewMockRepository(ctrl *gomock.Controller) *MockRepository {
	mock := &MockRepository{ctrl: ctrl}
	mock.recorder = &MockRepositoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockRepository) EXPECT() *MockRepositoryMockRecorder {
	return m.recorder
}

// BatchSave mocks base method.
func (m *MockRepository) BatchSave(arg0 context.Context, arg1 []models.URL, arg2 uuid.UUID, arg3 int, arg4 string) ([]*models.ShortURL, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "BatchSave", arg0, arg1, arg2, arg3, arg4)
	ret0, _ := ret[0].([]*models.ShortURL)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// BatchSave indicates an expected call of BatchSave.
func (mr *MockRepositoryMockRecorder) BatchSave(arg0, arg1, arg2, arg3, arg4 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "BatchSave", reflect.TypeOf((*MockRepository)(nil).BatchSave), arg0, arg1, arg2, arg3, arg4)
}

// FindAllByUserID mocks base method.
func (m *MockRepository) FindAllByUserID(arg0 context.Context, arg1 uuid.UUID) ([]*models.ShortURL, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FindAllByUserID", arg0, arg1)
	ret0, _ := ret[0].([]*models.ShortURL)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// FindAllByUserID indicates an expected call of FindAllByUserID.
func (mr *MockRepositoryMockRecorder) FindAllByUserID(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FindAllByUserID", reflect.TypeOf((*MockRepository)(nil).FindAllByUserID), arg0, arg1)
}

// FindOneByUID mocks base method.
func (m *MockRepository) FindOneByUID(arg0 context.Context, arg1 models.UID) (*models.ShortURL, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FindOneByUID", arg0, arg1)
	ret0, _ := ret[0].(*models.ShortURL)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// FindOneByUID indicates an expected call of FindOneByUID.
func (mr *MockRepositoryMockRecorder) FindOneByUID(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FindOneByUID", reflect.TypeOf((*MockRepository)(nil).FindOneByUID), arg0, arg1)
}

// Ping mocks base method.
func (m *MockRepository) Ping(arg0 context.Context) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Ping", arg0)
	ret0, _ := ret[0].(error)
	return ret0
}

// Ping indicates an expected call of Ping.
func (mr *MockRepositoryMockRecorder) Ping(arg0 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Ping", reflect.TypeOf((*MockRepository)(nil).Ping), arg0)
}

// Save mocks base method.
func (m *MockRepository) Save(arg0 context.Context, arg1 models.URL, arg2 uuid.UUID, arg3 int, arg4 string) (*models.ShortURL, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Save", arg0, arg1, arg2, arg3, arg4)
	ret0, _ := ret[0].(*models.ShortURL)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Save indicates an expected call of Save.
func (mr *MockRepositoryMockRecorder) Save(arg0, arg1, arg2, arg3, arg4 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Save", reflect.TypeOf((*MockRepository)(nil).Save), arg0, arg1, arg2, arg3, arg4)
}
